service: parser-proto-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-south-2
  memorySize: 128
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    EVENTS_TABLE: ${opt:stage, self:provider.stage}-events
    API_KEY: ${ssm:/event-service/${opt:stage, self:provider.stage}/api-key}
    EVENT_SERVICE_BASE_URL:  https://9o2hcnr4ig.execute-api.eu-south-2.amazonaws.com/dev

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-middleware

package:
  individually: true

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

functions:
  createEvent:
    handler: src/handlers/create.createEvent
    events:
      - http:
          path: events
          method: get
          cors: true