service: notification-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-south-2
  memorySize: 128
  environment:
    API_KEY: ${ssm:/event-service/${opt:stage, self:provider.stage}/api-key}
    TELEGRAM_TOKEN: ${ssm:telegram-tmp-token}
    TELEGRAM_CHAT_ID: ${ssm:telegram-tmp-chat-id}

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true

functions:
  notify:
    handler: src/handlers/notify.handler
    timeout: 30
    events:
      - http:
          path: notify
          method: post
          cors: true