service: event-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-south-2
  memorySize: 128
  environment:
    API_KEY: ${ssm:/event-service/${opt:stage, self:provider.stage}/api-key}
    MONGO_URI: ${ssm:/event-service/${opt:stage, self:provider.stage}/mongo-uri}
    NOTIFY_SERVICE_BASE_URL: ${ssm:/notification-service/${opt:stage, self:provider.stage}/api-url,  'https://6s8vekl6ij.execute-api.eu-south-2.amazonaws.com/dev'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:table/*"

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true

functions:
  createEvent:
    handler: src/handlers/create.createHandler
    events:
      - http:
          path: events
          method: put
          cors: true

  upsertEvent:
    handler: src/handlers/upsert.upsertHandler
    events:
      - http:
          path: events/upsert
          method: post
          cors: true

  getEvent:
    handler: src/handlers/get.getHandler
    events:
      - http:
          path: events/{id}
          method: get
          cors: true

  listEvents:
    handler: src/handlers/list.listHandler
    events:
      - http:
          path: events
          method: get
          cors: true
    timeout: 30

  countEvents:
    handler: src/handlers/count.countHandler
    events:
      - http:
          path: events/count
          method: get
          cors: true
    timeout: 30

  updateEvent:
    handler: src/handlers/update.updateHandler
    events:
      - http:
          path: events/{id}
          method: patch
          cors: true

  deleteEvent:
    handler: src/handlers/delete.deleteHandler
    events:
      - http:
          path: events/{id}
          method: delete
          cors: true

resources:
  Resources:
    EventsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.stage}-events
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
